apiVersion: v1
kind: Secret
metadata:
  name: karpl-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  LINODE_TOKEN: {{ required "The API token needs to be set" .Values.apiToken }}
  LINODE_URL: {{ .Values.apiURL }}
  LINODE_API_VERSION: {{ .Values.apiVersion }}
  LKE_CLUSTER_ID: {{ required "The LKE cluster ID needs to be set" .Values.settings.clusterID | quote }}
  # TODO: region discovery
  CLUSTER_REGION: {{ required "The cluster region currently needs to be set" .Values.region }}
