apiVersion: v1
kind: Secret
metadata:
  name: karpl-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  LINODE_TOKEN: {{ .Values.apiToken }}
  LINODE_URL: {{ .Values.apiURL }}
  LINODE_API_VERSION: {{ .Values.apiVersion }}
