apiVersion: v1
kind: Secret
metadata:
  name: karpl-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  LINODE_TOKEN: {{ required "The API token needs to be set" .Values.apiToken }}
  LINODE_URL: {{ .Values.apiURL }}
  LINODE_API_VERSION: {{ .Values.apiVersion }}
  {{- if .Values.region }}
  CLUSTER_REGION: {{ .Values.region }}
  {{- end }}
